SELECT X.AUTHOR_ID, A.AUTHOR_NAME, X.CATEGORY, SUM(X.TEMP_SALES) AS TOTAL_SALES
FROM (
    SELECT B.BOOK_ID, CATEGORY, AUTHOR_ID, SUM(B.PRICE * BS.SALES) AS TEMP_SALES
    FROM BOOK B JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID
    WHERE BS.SALES_DATE LIKE '2022-01%'
    GROUP BY BOOK_ID
    ) X JOIN AUTHOR A ON X.AUTHOR_ID = A.AUTHOR_ID
GROUP BY X.AUTHOR_ID, X.CATEGORY
ORDER BY 1 ASC, 3 DESC