SELECT CART_ID
FROM (
    SELECT 
    CART_ID, 
    SUM(CASE WHEN NAME = 'Milk' THEN 1 ELSE 0 END) AS M,
    SUM(CASE WHEN NAME = 'Yogurt' THEN 1 ELSE 0 END) AS Y
    FROM CART_PRODUCTS
    GROUP BY CART_ID
    ) X
WHERE M > 0 AND Y > 0
ORDER BY CART_ID