WITH RECURSIVE TREE AS (
    SELECT 
        ID,
        PARENT_ID,
        1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT 
        A.ID,
        A.PARENT_ID,
        B.GENERATION + 1
    FROM ECOLI_DATA A JOIN TREE B ON A.PARENT_ID = B.ID
)

SELECT ID
FROM TREE
WHERE GENERATION = 3