WITH B AS (
    SELECT 
        CAR_ID,
        SUM(
            CASE 
                WHEN END_DATE < '2022-11-1' OR START_DATE > '2022-11-30'
                THEN 0
                ELSE 1
            END
        ) AS FLAG
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
),
     C AS (
    SELECT 
        CAR_TYPE,
        CAST(REGEXP_SUBSTR(DURATION_TYPE, '[0-9]+') AS UNSIGNED) AS DURATION_TYPE,
        CAST(REGEXP_SUBSTR(DISCOUNT_RATE, '[0-9]+') AS UNSIGNED) AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = 30
)

SELECT 
    A.CAR_ID, 
    A.CAR_TYPE,
    A.DAILY_FEE * 30 * (100 - C.DISCOUNT_RATE) / 100 AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
    LEFT JOIN
    B
    ON A.CAR_ID = B.CAR_ID
    JOIN
    C
    ON A.CAR_TYPE = C.CAR_TYPE
WHERE A.CAR_TYPE IN ('세단', 'SUV') AND (B.FLAG IS NULL OR B.FLAG = 0)
GROUP BY CAR_ID
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC