-- 코드를 입력하세요
SELECT A.FOOD_TYPE FOOD_TYPE, A.REST_ID REST_ID, A.REST_NAME REST_NAME, B.MAX_FAVOR AS FAVORITES
FROM REST_INFO A JOIN (
    SELECT FOOD_TYPE, REST_NAME, MAX(FAVORITES) MAX_FAVOR
    FROM REST_INFO
    GROUP BY FOOD_TYPE
    ) B
    ON A.FOOD_TYPE = B.FOOD_TYPE AND A.FAVORITES = B.MAX_FAVOR
ORDER BY FOOD_TYPE DESC
