SELECT YEAR, MONTH, GENDER, COUNT(*) AS USERS
FROM (
    SELECT DISTINCT
    A.USER_ID,
    YEAR(SALES_DATE) AS YEAR, 
    MONTH(SALES_DATE) AS MONTH, 
    GENDER
    FROM USER_INFO A JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID AND A.GENDER IS NOT NULL    ) X
GROUP BY YEAR, MONTH, GENDER
ORDER BY 1 ASC, 2 ASC, 3 ASC