SELECT
    CAR_ID,
    CASE 
        WHEN SUM(FLAG) > 0
        THEN '대여중'
        ELSE '대여 가능'
    END AS AVAILABILITY
FROM 
    (SELECT
        CAR_ID,
        CASE 
            WHEN '2022-10-16' BETWEEN START_DATE AND END_DATE
            THEN 1
            ELSE 0
        END AS FLAG
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    ) A
GROUP BY CAR_ID
ORDER BY CAR_ID DESC