WITH B AS (
    SELECT HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS DUR
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
),
     C AS (
    SELECT 
        CAR_TYPE, 
        CAST(REGEXP_SUBSTR(DURATION_TYPE, '[0-9]+') AS UNSIGNED) AS DURATION_TYPE,
        CAST(REGEXP_SUBSTR(DISCOUNT_RATE, '[0-9]+') AS UNSIGNED) AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
)

SELECT HISTORY_ID, MIN((DUR * DAILY_FEE) * (100 - COALESCE(DISCOUNT_RATE, 0)) / 100) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR A
    JOIN
    B 
    ON A.CAR_TYPE = '트럭' AND A.CAR_ID = B.CAR_ID
    LEFT JOIN
    C
    ON A.CAR_TYPE = C.CAR_TYPE AND B.DUR >= C.DURATION_TYPE
GROUP BY 1
ORDER BY 2 DESC, 1 DESC