SELECT A.FLAVOR
FROM 
    (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_A FROM FIRST_HALF GROUP BY FLAVOR) A
    JOIN
    (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_B FROM JULY GROUP BY FLAVOR) B
    ON A.FLAVOR = B.FLAVOR
GROUP BY A.FLAVOR
ORDER BY (TOTAL_A + TOTAL_B) DESC
LIMIT 3