WITH RECURSIVE DUMMY AS (
    SELECT
        0 AS HOUR
    
    UNION ALL
    
    SELECT 
        HOUR + 1
    FROM DUMMY
    WHERE HOUR < 23
)

SELECT A.HOUR, COALESCE(B.COUNT, 0) AS HOUR
FROM 
    DUMMY A 
    LEFT JOIN
    (SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
     FROM ANIMAL_OUTS
     GROUP BY HOUR
    ) B
    ON A.HOUR = B.HOUR
ORDER BY 1