# SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
# FROM 
#     DEVELOPERS A
#     JOIN
#     SKILLCODES B
#     ON B.CATEGORY = 'Front End' AND B.CODE & A.SKILL_CODE > 0
# ORDER BY ID ASC

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS A
WHERE EXISTS (
    SELECT 1
    FROM SKILLCODES B
    WHERE B.CATEGORY = 'Front End' AND A.SKILL_CODE & B.CODE > 0
)
ORDER BY ID ASC