-- 코드를 입력하세요
SELECT B.USER_ID AS USER_ID, B.NICKNAME AS NICKNAME, SUM(A.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD A JOIN USED_GOODS_USER B ON A.STATUS = 'DONE' AND A.WRITER_ID = B.USER_ID
GROUP BY USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC
