SELECT 
    A.MEMBER_NAME, 
    B.REVIEW_TEXT, 
    DATE_FORMAT(B.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE A
JOIN REST_REVIEW B 
    ON A.MEMBER_ID = B.MEMBER_ID
JOIN (
    SELECT 
        MEMBER_ID,
        RANK() OVER (ORDER BY COUNT(*) DESC) AS rnk
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
) C
    ON B.MEMBER_ID = C.MEMBER_ID
WHERE C.rnk = 1
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;