-- 코드를 입력하세요
SELECT 
    A.MEMBER_NAME, 
    B.REVIEW_TEXT, 
    DATE_FORMAT(B.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM 
    MEMBER_PROFILE A 
    JOIN
    REST_REVIEW B
    JOIN (
        SELECT MEMBER_ID, COUNT(*) AS CNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY CNT DESC
        LIMIT 1
    ) C
    ON B.MEMBER_ID = C.MEMBER_ID AND A.MEMBER_ID = B.MEMBER_ID
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC