SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (
    SELECT A.ITEM_ID
    FROM 
        ITEM_TREE A
        JOIN
        ITEM_INFO B
        ON A.PARENT_ITEM_ID = B.ITEM_ID AND B.RARITY = 'RARE'
    )
ORDER BY 1 DESC