SELECT MONTH(START_DATE), A.CAR_ID, COUNT(*) AS RECORDS
FROM 
    (
    SELECT CAR_ID, COUNT(*) AS CNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING CNT >= 5
    ) A
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    ON A.CAR_ID = B.CAR_ID
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH(START_DATE), CAR_ID
HAVING RECORDS >= 0
ORDER BY 1 ASC, 2 DESC