SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM (SELECT * FROM DEVELOPERS AS A
JOIN (SELECT * FROM SKILLCODES) B
ON B.NAME IN ('PYTHON', 'C#') AND A.SKILL_CODE & B.CODE = B.CODE) X
ORDER BY ID ASC