-- 코드를 입력하세요
# SELECT CATEGORY, COUNT(*) FROM (
#     SELECT SUBSTR(PRODUCT_CODE, 1, 2) AS CATEGORY
#     FROM PRODUCT
# ) X
# GROUP BY CATEGORY
# ORDER BY CATEGORY;

SELECT SUBSTR(PRODUCT_CODE, 1, 2) AS CATEGORY, COUNT(SUBSTR(PRODUCT_CODE, 1, 2))
FROM PRODUCT
GROUP BY CATEGORY;