-- 코드를 작성해주세요
SELECT A.DEPT_ID DEPT_ID, A.DEPT_NAME_EN DEPT_NAME_EN, ROUND(SUM(B.SAL) / COUNT(*), 0) AS AVG_SAL
FROM HR_DEPARTMENT A RIGHT JOIN HR_EMPLOYEES B ON A.DEPT_ID = B.DEPT_ID
GROUP BY DEPT_ID
ORDER BY AVG_SAL DESC