-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES)
FROM (
    SELECT BOOK.CATEGORY AS CATEGORY, BOOK_SALES.SALES AS SALES
    FROM BOOK LEFT JOIN BOOK_SALES ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
    WHERE YEAR(BOOK_SALES.SALES_DATE) = '2022' AND MONTH(BOOK_SALES.SALES_DATE) = '1'
    
) X
GROUP BY CATEGORY
ORDER BY CATEGORY ASC