-- 코드를 입력하세요
SELECT A.CATEGORY AS CATEGORY, A.PRICE AS MAX_RPICE, A.PRODUCT_NAME AS PRODUCT_NAME
FROM FOOD_PRODUCT A RIGHT JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
    ) B
    ON A.CATEGORY = B.CATEGORY AND A.PRICE = B.MAX_PRICE
ORDER BY MAX_PRICE DESC